// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module word_width_manual_word_width_manual_Pipeline_WRITE (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_read3_V_load,
        x_sel_rd_V_load,
        y_Addr_A,
        y_EN_A,
        y_WEN_A,
        y_Din_A,
        y_Dout_A,
        x_read3_V_flag_0_out,
        x_read3_V_flag_0_out_ap_vld,
        x_read3_V_new_0_out,
        x_read3_V_new_0_out_ap_vld,
        t_V_out,
        t_V_out_ap_vld,
        x_x_V_address0,
        x_x_V_ce0,
        x_x_V_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] x_read3_V_load;
input  [1:0] x_sel_rd_V_load;
output  [31:0] y_Addr_A;
output   y_EN_A;
output  [0:0] y_WEN_A;
output  [7:0] y_Din_A;
input  [7:0] y_Dout_A;
output  [0:0] x_read3_V_flag_0_out;
output   x_read3_V_flag_0_out_ap_vld;
output  [23:0] x_read3_V_new_0_out;
output   x_read3_V_new_0_out_ap_vld;
output  [1:0] t_V_out;
output   t_V_out_ap_vld;
output  [18:0] x_x_V_address0;
output   x_x_V_ce0;
input  [23:0] x_x_V_q0;

reg ap_idle;
reg y_EN_A;
reg[0:0] y_WEN_A;
reg x_read3_V_flag_0_out_ap_vld;
reg x_read3_V_new_0_out_ap_vld;
reg t_V_out_ap_vld;
reg x_x_V_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln25_fu_185_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] x_read3_V_flag_0_reg_155;
reg   [0:0] icmp_ln25_reg_441;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln25_fu_197_p1;
reg   [63:0] zext_ln25_reg_445;
wire   [0:0] or_ln1064_2_fu_322_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [1:0] t_V_fu_80;
wire   [1:0] select_ln17_fu_358_p3;
reg   [18:0] i_V_1_fu_84;
wire   [18:0] i_fu_191_p2;
reg   [18:0] ap_sig_allocacmp_i_V;
reg   [23:0] p_Val2_s_fu_88;
wire   [23:0] p_Val2_3_fu_344_p3;
reg   [23:0] x_read3_V_new_0_fu_92;
wire   [23:0] select_ln1064_1_fu_336_p3;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] y_Addr_A_orig;
wire   [0:0] icmp_ln1064_fu_222_p2;
wire   [1:0] add_ln885_fu_216_p2;
wire   [0:0] icmp_ln1064_1_fu_236_p2;
wire   [23:0] p_Val2_1_fu_228_p3;
wire   [1:0] t_V_1_fu_242_p3;
wire   [0:0] icmp_ln1064_2_fu_260_p2;
wire   [1:0] add_ln885_1_fu_254_p2;
wire   [0:0] icmp_ln1064_3_fu_274_p2;
wire   [23:0] p_Val2_2_fu_266_p3;
wire   [1:0] t_V_2_fu_280_p3;
wire   [0:0] icmp_ln1064_4_fu_304_p2;
wire   [0:0] or_ln1064_fu_310_p2;
wire   [0:0] or_ln1064_1_fu_316_p2;
wire   [23:0] select_ln1064_fu_328_p3;
wire   [1:0] add_ln885_2_fu_298_p2;
wire   [0:0] icmp_ln1064_5_fu_352_p2;
wire   [7:0] tmp_V_fu_250_p1;
wire   [7:0] tmp_V_2_fu_366_p4;
wire   [7:0] add_ln70_fu_376_p2;
wire   [7:0] tmp_V_1_fu_288_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_299;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

word_width_manual_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln25_fu_185_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_V_1_fu_84 <= i_fu_191_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_V_1_fu_84 <= 19'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_Val2_s_fu_88 <= x_read3_V_load;
        end else if (((icmp_ln25_reg_441 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_Val2_s_fu_88 <= p_Val2_3_fu_344_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            t_V_fu_80 <= x_sel_rd_V_load;
        end else if (((icmp_ln25_reg_441 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            t_V_fu_80 <= select_ln17_fu_358_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_299)) begin
            x_read3_V_flag_0_reg_155 <= or_ln1064_2_fu_322_p2;
        end else if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            x_read3_V_flag_0_reg_155 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln25_reg_441 <= icmp_ln25_fu_185_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln25_reg_441 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_read3_V_new_0_fu_92 <= select_ln1064_1_fu_336_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln25_fu_185_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln25_reg_445[18 : 0] <= zext_ln25_fu_197_p1[18 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln25_fu_185_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_V = 19'd0;
    end else begin
        ap_sig_allocacmp_i_V = i_V_1_fu_84;
    end
end

always @ (*) begin
    if (((icmp_ln25_fu_185_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        t_V_out_ap_vld = 1'b1;
    end else begin
        t_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln25_fu_185_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_read3_V_flag_0_out_ap_vld = 1'b1;
    end else begin
        x_read3_V_flag_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln25_fu_185_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_read3_V_new_0_out_ap_vld = 1'b1;
    end else begin
        x_read3_V_new_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_x_V_ce0 = 1'b1;
    end else begin
        x_x_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y_EN_A = 1'b1;
    end else begin
        y_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln25_reg_441 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y_WEN_A = 1'd1;
    end else begin
        y_WEN_A = 1'd0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln70_fu_376_p2 = (tmp_V_fu_250_p1 + tmp_V_2_fu_366_p4);

assign add_ln885_1_fu_254_p2 = (t_V_1_fu_242_p3 + 2'd1);

assign add_ln885_2_fu_298_p2 = (t_V_2_fu_280_p3 + 2'd1);

assign add_ln885_fu_216_p2 = (t_V_fu_80 + 2'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_299 = ((icmp_ln25_reg_441 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign i_fu_191_p2 = (ap_sig_allocacmp_i_V + 19'd1);

assign icmp_ln1064_1_fu_236_p2 = ((add_ln885_fu_216_p2 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln1064_2_fu_260_p2 = ((t_V_1_fu_242_p3 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln1064_3_fu_274_p2 = ((add_ln885_1_fu_254_p2 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln1064_4_fu_304_p2 = ((t_V_2_fu_280_p3 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln1064_5_fu_352_p2 = ((add_ln885_2_fu_298_p2 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln1064_fu_222_p2 = ((t_V_fu_80 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln25_fu_185_p2 = ((ap_sig_allocacmp_i_V == 19'd409600) ? 1'b1 : 1'b0);

assign or_ln1064_1_fu_316_p2 = (or_ln1064_fu_310_p2 | icmp_ln1064_fu_222_p2);

assign or_ln1064_2_fu_322_p2 = (x_read3_V_flag_0_reg_155 | or_ln1064_1_fu_316_p2);

assign or_ln1064_fu_310_p2 = (icmp_ln1064_4_fu_304_p2 | icmp_ln1064_2_fu_260_p2);

assign p_Val2_1_fu_228_p3 = ((icmp_ln1064_fu_222_p2[0:0] == 1'b1) ? x_x_V_q0 : p_Val2_s_fu_88);

assign p_Val2_2_fu_266_p3 = ((icmp_ln1064_2_fu_260_p2[0:0] == 1'b1) ? x_x_V_q0 : p_Val2_1_fu_228_p3);

assign p_Val2_3_fu_344_p3 = ((icmp_ln1064_4_fu_304_p2[0:0] == 1'b1) ? x_x_V_q0 : p_Val2_2_fu_266_p3);

assign select_ln1064_1_fu_336_p3 = ((or_ln1064_fu_310_p2[0:0] == 1'b1) ? x_x_V_q0 : select_ln1064_fu_328_p3);

assign select_ln1064_fu_328_p3 = ((icmp_ln1064_fu_222_p2[0:0] == 1'b1) ? x_x_V_q0 : x_read3_V_new_0_fu_92);

assign select_ln17_fu_358_p3 = ((icmp_ln1064_5_fu_352_p2[0:0] == 1'b1) ? 2'd0 : add_ln885_2_fu_298_p2);

assign t_V_1_fu_242_p3 = ((icmp_ln1064_1_fu_236_p2[0:0] == 1'b1) ? 2'd0 : add_ln885_fu_216_p2);

assign t_V_2_fu_280_p3 = ((icmp_ln1064_3_fu_274_p2[0:0] == 1'b1) ? 2'd0 : add_ln885_1_fu_254_p2);

assign t_V_out = t_V_fu_80;

assign tmp_V_1_fu_288_p4 = {{p_Val2_2_fu_266_p3[15:8]}};

assign tmp_V_2_fu_366_p4 = {{p_Val2_3_fu_344_p3[23:16]}};

assign tmp_V_fu_250_p1 = p_Val2_1_fu_228_p3[7:0];

assign x_read3_V_flag_0_out = x_read3_V_flag_0_reg_155;

assign x_read3_V_new_0_out = x_read3_V_new_0_fu_92;

assign x_x_V_address0 = zext_ln25_fu_197_p1;

assign y_Addr_A = y_Addr_A_orig << 32'd0;

assign y_Addr_A_orig = zext_ln25_reg_445;

assign y_Din_A = (add_ln70_fu_376_p2 + tmp_V_1_fu_288_p4);

assign zext_ln25_fu_197_p1 = ap_sig_allocacmp_i_V;

always @ (posedge ap_clk) begin
    zext_ln25_reg_445[63:19] <= 45'b000000000000000000000000000000000000000000000;
end

endmodule //word_width_manual_word_width_manual_Pipeline_WRITE
