-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity window_avg_buff is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    din : IN STD_LOGIC_VECTOR (7 downto 0);
    c : IN STD_LOGIC_VECTOR (9 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of window_avg_buff is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal guard_variable_for_buff_ap_uint_8_int_ap_uint_8_sel : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal sel : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal buff1_cnt_V : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal buff1_write_data_V : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal buff1_ram_V_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal buff1_ram_V_ce0 : STD_LOGIC;
    signal buff1_ram_V_we0 : STD_LOGIC;
    signal buff1_ram_V_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal buff1_ram_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal buff1_read_data_V : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal buff0_cnt_V : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal buff0_write_data_V : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal buff0_ram_V_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal buff0_ram_V_ce0 : STD_LOGIC;
    signal buff0_ram_V_we0 : STD_LOGIC;
    signal buff0_ram_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal buff0_read_data_V : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal empty_reg_114 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_20_reg_270 : STD_LOGIC_VECTOR (0 downto 0);
    signal c_read_reg_592 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal din_read_reg_597 : STD_LOGIC_VECTOR (7 downto 0);
    signal din_read_reg_597_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln38_fu_344_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_607 : STD_LOGIC_VECTOR (0 downto 0);
    signal buff1_cnt_V_load_load_fu_350_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal buff1_cnt_V_load_reg_611 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln885_2_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln674_1_fu_435_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal buff0_cnt_V_load_load_fu_453_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal buff0_cnt_V_load_reg_636 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_empty_phi_fu_117_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_reg_114 : STD_LOGIC_VECTOR (0 downto 0);
    signal guard_variable_for_buff_ap_uint_8_int_ap_uint_8_sel_load_load_fu_329_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_sel_flag_0_reg_125 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_sel_flag_0_reg_125 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_sel_flag_1_phi_fu_142_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_sel_flag_1_reg_138 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_sel_flag_1_reg_138 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_sel_new_1_phi_fu_153_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_sel_new_1_reg_150 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_sel_new_1_reg_150 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_sel_flag_2_phi_fu_164_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_sel_flag_2_reg_160 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_sel_flag_2_reg_160 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_sel_new_2_phi_fu_175_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_sel_new_2_reg_172 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_sel_new_2_reg_172 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_sel_flag_3_phi_fu_185_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_sel_flag_3_reg_182 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_sel_new_3_phi_fu_196_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_sel_new_3_reg_193 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_empty_19_phi_fu_207_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_empty_19_reg_204 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_sel_flag_4_phi_fu_218_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_sel_flag_4_reg_215 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_sel_new_4_phi_fu_229_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_sel_new_4_reg_226 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_p_ph_phi_fu_240_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_p_ph_reg_237 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_sel_flag_5_phi_fu_251_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_sel_flag_5_reg_248 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_sel_new_5_phi_fu_262_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_sel_new_5_reg_259 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_empty_20_phi_fu_273_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_empty_20_reg_270 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_buff0_write_data_V_loc_0_phi_fu_285_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_buff0_write_data_V_loc_0_reg_282 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_4_fu_496_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tmp_4_reg_292 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_tmp_4_reg_292 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_tmp_4_reg_292 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_tmp_5_phi_fu_304_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln674_3_fu_539_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_tmp_5_reg_301 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln56_fu_407_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln52_fu_412_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln52_1_fu_511_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln56_1_fu_516_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_sel_load : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln885_fu_417_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_1_fu_374_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_fu_392_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal xor_ln885_1_fu_521_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_364_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln674_fu_388_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_310_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln674_2_fu_468_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_479_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_2_fu_472_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_3_fu_489_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_320_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_fu_559_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln46_fu_567_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_156 : BOOLEAN;
    signal ap_condition_169 : BOOLEAN;
    signal ap_condition_273 : BOOLEAN;
    signal ap_condition_268 : BOOLEAN;
    signal ap_condition_262 : BOOLEAN;
    signal ap_condition_291 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component window_avg_buff_buff1_ram_V_RAM_1P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    buff1_ram_V_U : component window_avg_buff_buff1_ram_V_RAM_1P_BRAM_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 320,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buff1_ram_V_address0,
        ce0 => buff1_ram_V_ce0,
        we0 => buff1_ram_V_we0,
        d0 => buff1_ram_V_d0,
        q0 => buff1_ram_V_q0);

    buff0_ram_V_U : component window_avg_buff_buff1_ram_V_RAM_1P_BRAM_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 320,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buff0_ram_V_address0,
        ce0 => buff0_ram_V_ce0,
        we0 => buff0_ram_V_we0,
        d0 => ap_phi_mux_buff0_write_data_V_loc_0_phi_fu_285_p4,
        q0 => buff0_ram_V_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_sel_flag_0_reg_125_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_156)) then
                if ((guard_variable_for_buff_ap_uint_8_int_ap_uint_8_sel_load_load_fu_329_p1 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_sel_flag_0_reg_125 <= ap_const_lv1_0;
                elsif ((guard_variable_for_buff_ap_uint_8_int_ap_uint_8_sel_load_load_fu_329_p1 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter1_sel_flag_0_reg_125 <= ap_const_lv1_1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_sel_flag_0_reg_125 <= ap_phi_reg_pp0_iter0_sel_flag_0_reg_125;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_sel_flag_1_reg_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_156)) then
                if (((ap_phi_mux_empty_phi_fu_117_p4 = ap_const_lv1_0) and (icmp_ln38_fu_344_p2 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter1_sel_flag_1_reg_138 <= ap_const_lv1_1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_sel_flag_1_reg_138 <= ap_phi_reg_pp0_iter0_sel_flag_1_reg_138;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_sel_flag_2_reg_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_156)) then
                if (((ap_phi_mux_empty_phi_fu_117_p4 = ap_const_lv1_1) and (icmp_ln38_fu_344_p2 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter1_sel_flag_2_reg_160 <= ap_const_lv1_1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_sel_flag_2_reg_160 <= ap_phi_reg_pp0_iter0_sel_flag_2_reg_160;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_sel_new_1_reg_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_156)) then
                if (((ap_phi_mux_empty_phi_fu_117_p4 = ap_const_lv1_0) and (icmp_ln38_fu_344_p2 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter1_sel_new_1_reg_150 <= xor_ln885_2_fu_354_p2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_sel_new_1_reg_150 <= ap_phi_reg_pp0_iter0_sel_new_1_reg_150;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_sel_new_2_reg_172_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_156)) then
                if (((ap_phi_mux_empty_phi_fu_117_p4 = ap_const_lv1_1) and (icmp_ln38_fu_344_p2 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter1_sel_new_2_reg_172 <= xor_ln885_2_fu_354_p2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_sel_new_2_reg_172 <= ap_phi_reg_pp0_iter0_sel_new_2_reg_172;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_tmp_4_reg_292_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_169)) then
                if ((buff1_cnt_V_load_reg_611 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter2_tmp_4_reg_292 <= trunc_ln674_1_fu_435_p1;
                elsif ((buff1_cnt_V_load_reg_611 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter2_tmp_4_reg_292 <= buff1_read_data_V(15 downto 8);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_tmp_4_reg_292 <= ap_phi_reg_pp0_iter1_tmp_4_reg_292;
                end if;
            end if; 
        end if;
    end process;

    buff1_write_data_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_156)) then
                if ((ap_const_boolean_1 = ap_condition_268)) then 
                    buff1_write_data_V <= ret_fu_392_p3;
                elsif ((ap_const_boolean_1 = ap_condition_291)) then 
                    buff1_write_data_V <= ret_1_fu_374_p3;
                end if;
            end if; 
        end if;
    end process;

    empty_20_reg_270_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_169)) then
                if ((buff1_cnt_V_load_reg_611 = ap_const_lv1_0)) then 
                    empty_20_reg_270 <= ap_phi_mux_empty_19_phi_fu_207_p4;
                elsif ((buff1_cnt_V_load_reg_611 = ap_const_lv1_1)) then 
                    empty_20_reg_270 <= ap_phi_mux_p_ph_phi_fu_240_p4;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    empty_20_reg_270 <= ap_phi_reg_pp0_iter1_empty_20_reg_270;
                end if;
            end if; 
        end if;
    end process;

    empty_reg_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_156)) then
                if ((guard_variable_for_buff_ap_uint_8_int_ap_uint_8_sel_load_load_fu_329_p1 = ap_const_lv1_1)) then 
                    empty_reg_114 <= ap_sig_allocacmp_sel_load;
                elsif ((guard_variable_for_buff_ap_uint_8_int_ap_uint_8_sel_load_load_fu_329_p1 = ap_const_lv1_0)) then 
                    empty_reg_114 <= ap_const_lv1_1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    empty_reg_114 <= ap_phi_reg_pp0_iter0_empty_reg_114;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter1_tmp_4_reg_292 <= ap_phi_reg_pp0_iter0_tmp_4_reg_292;
                buff1_cnt_V <= xor_ln885_fu_417_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                buff0_cnt_V <= xor_ln885_1_fu_521_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                buff0_cnt_V_load_reg_636 <= buff0_cnt_V;
                buff1_cnt_V_load_reg_611 <= buff1_cnt_V;
                c_read_reg_592 <= c;
                din_read_reg_597 <= din;
                din_read_reg_597_pp0_iter1_reg <= din_read_reg_597;
                icmp_ln38_reg_607 <= icmp_ln38_fu_344_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (buff0_cnt_V_load_reg_636 = ap_const_lv1_0))) then
                buff0_read_data_V <= buff0_ram_V_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_phi_mux_empty_20_phi_fu_273_p4 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                buff0_write_data_V <= ret_4_fu_496_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_0))) then
                buff1_read_data_V <= buff1_ram_V_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (guard_variable_for_buff_ap_uint_8_int_ap_uint_8_sel_load_load_fu_329_p1 = ap_const_lv1_0))) then
                guard_variable_for_buff_ap_uint_8_int_ap_uint_8_sel <= ap_const_lv1_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_phi_mux_sel_flag_5_phi_fu_251_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                sel <= ap_phi_mux_sel_new_5_phi_fu_262_p4;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_156_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
                ap_condition_156 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_169_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
                ap_condition_169 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_262_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0)
    begin
                ap_condition_262 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_268_assign_proc : process(icmp_ln38_fu_344_p2, buff1_cnt_V_load_load_fu_350_p1, ap_phi_mux_empty_phi_fu_117_p4)
    begin
                ap_condition_268 <= (((ap_phi_mux_empty_phi_fu_117_p4 = ap_const_lv1_1) and (buff1_cnt_V_load_load_fu_350_p1 = ap_const_lv1_1) and (icmp_ln38_fu_344_p2 = ap_const_lv1_0)) or ((ap_phi_mux_empty_phi_fu_117_p4 = ap_const_lv1_0) and (buff1_cnt_V_load_load_fu_350_p1 = ap_const_lv1_1) and (icmp_ln38_fu_344_p2 = ap_const_lv1_1)));
    end process;


    ap_condition_273_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
                ap_condition_273 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_291_assign_proc : process(icmp_ln38_fu_344_p2, buff1_cnt_V_load_load_fu_350_p1, ap_phi_mux_empty_phi_fu_117_p4)
    begin
                ap_condition_291 <= (((ap_phi_mux_empty_phi_fu_117_p4 = ap_const_lv1_1) and (buff1_cnt_V_load_load_fu_350_p1 = ap_const_lv1_0) and (icmp_ln38_fu_344_p2 = ap_const_lv1_0)) or ((ap_phi_mux_empty_phi_fu_117_p4 = ap_const_lv1_0) and (buff1_cnt_V_load_load_fu_350_p1 = ap_const_lv1_0) and (icmp_ln38_fu_344_p2 = ap_const_lv1_1)));
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_buff0_write_data_V_loc_0_phi_fu_285_p4_assign_proc : process(buff0_write_data_V, ap_phi_mux_empty_20_phi_fu_273_p4, ap_phi_reg_pp0_iter1_buff0_write_data_V_loc_0_reg_282, ret_4_fu_496_p3)
    begin
        if ((ap_phi_mux_empty_20_phi_fu_273_p4 = ap_const_lv1_0)) then 
            ap_phi_mux_buff0_write_data_V_loc_0_phi_fu_285_p4 <= ret_4_fu_496_p3;
        elsif ((ap_phi_mux_empty_20_phi_fu_273_p4 = ap_const_lv1_1)) then 
            ap_phi_mux_buff0_write_data_V_loc_0_phi_fu_285_p4 <= buff0_write_data_V;
        else 
            ap_phi_mux_buff0_write_data_V_loc_0_phi_fu_285_p4 <= ap_phi_reg_pp0_iter1_buff0_write_data_V_loc_0_reg_282;
        end if; 
    end process;


    ap_phi_mux_empty_19_phi_fu_207_p4_assign_proc : process(empty_reg_114, icmp_ln38_reg_607, buff1_cnt_V_load_reg_611, ap_phi_reg_pp0_iter1_empty_19_reg_204)
    begin
        if ((((empty_reg_114 = ap_const_lv1_0) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_0) and (icmp_ln38_reg_607 = ap_const_lv1_1)) or ((empty_reg_114 = ap_const_lv1_1) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_0) and (icmp_ln38_reg_607 = ap_const_lv1_0)))) then 
            ap_phi_mux_empty_19_phi_fu_207_p4 <= ap_const_lv1_1;
        elsif ((((empty_reg_114 = ap_const_lv1_0) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_0) and (icmp_ln38_reg_607 = ap_const_lv1_0)) or ((empty_reg_114 = ap_const_lv1_1) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_0) and (icmp_ln38_reg_607 = ap_const_lv1_1)))) then 
            ap_phi_mux_empty_19_phi_fu_207_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_empty_19_phi_fu_207_p4 <= ap_phi_reg_pp0_iter1_empty_19_reg_204;
        end if; 
    end process;


    ap_phi_mux_empty_20_phi_fu_273_p4_assign_proc : process(buff1_cnt_V_load_reg_611, ap_phi_mux_empty_19_phi_fu_207_p4, ap_phi_mux_p_ph_phi_fu_240_p4, ap_phi_reg_pp0_iter1_empty_20_reg_270)
    begin
        if ((buff1_cnt_V_load_reg_611 = ap_const_lv1_0)) then 
            ap_phi_mux_empty_20_phi_fu_273_p4 <= ap_phi_mux_empty_19_phi_fu_207_p4;
        elsif ((buff1_cnt_V_load_reg_611 = ap_const_lv1_1)) then 
            ap_phi_mux_empty_20_phi_fu_273_p4 <= ap_phi_mux_p_ph_phi_fu_240_p4;
        else 
            ap_phi_mux_empty_20_phi_fu_273_p4 <= ap_phi_reg_pp0_iter1_empty_20_reg_270;
        end if; 
    end process;


    ap_phi_mux_empty_phi_fu_117_p4_assign_proc : process(ap_phi_reg_pp0_iter0_empty_reg_114, guard_variable_for_buff_ap_uint_8_int_ap_uint_8_sel_load_load_fu_329_p1, ap_sig_allocacmp_sel_load)
    begin
        if ((guard_variable_for_buff_ap_uint_8_int_ap_uint_8_sel_load_load_fu_329_p1 = ap_const_lv1_1)) then 
            ap_phi_mux_empty_phi_fu_117_p4 <= ap_sig_allocacmp_sel_load;
        elsif ((guard_variable_for_buff_ap_uint_8_int_ap_uint_8_sel_load_load_fu_329_p1 = ap_const_lv1_0)) then 
            ap_phi_mux_empty_phi_fu_117_p4 <= ap_const_lv1_1;
        else 
            ap_phi_mux_empty_phi_fu_117_p4 <= ap_phi_reg_pp0_iter0_empty_reg_114;
        end if; 
    end process;


    ap_phi_mux_p_ph_phi_fu_240_p4_assign_proc : process(empty_reg_114, icmp_ln38_reg_607, buff1_cnt_V_load_reg_611, ap_phi_reg_pp0_iter1_p_ph_reg_237)
    begin
        if ((((empty_reg_114 = ap_const_lv1_0) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_1) and (icmp_ln38_reg_607 = ap_const_lv1_1)) or ((empty_reg_114 = ap_const_lv1_1) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_1) and (icmp_ln38_reg_607 = ap_const_lv1_0)))) then 
            ap_phi_mux_p_ph_phi_fu_240_p4 <= ap_const_lv1_1;
        elsif ((((empty_reg_114 = ap_const_lv1_0) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_1) and (icmp_ln38_reg_607 = ap_const_lv1_0)) or ((empty_reg_114 = ap_const_lv1_1) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_1) and (icmp_ln38_reg_607 = ap_const_lv1_1)))) then 
            ap_phi_mux_p_ph_phi_fu_240_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_p_ph_phi_fu_240_p4 <= ap_phi_reg_pp0_iter1_p_ph_reg_237;
        end if; 
    end process;


    ap_phi_mux_sel_flag_1_phi_fu_142_p4_assign_proc : process(empty_reg_114, icmp_ln38_reg_607, ap_phi_reg_pp0_iter1_sel_flag_0_reg_125, ap_phi_reg_pp0_iter1_sel_flag_1_reg_138)
    begin
        if (((empty_reg_114 = ap_const_lv1_1) and (icmp_ln38_reg_607 = ap_const_lv1_0))) then 
            ap_phi_mux_sel_flag_1_phi_fu_142_p4 <= ap_phi_reg_pp0_iter1_sel_flag_0_reg_125;
        else 
            ap_phi_mux_sel_flag_1_phi_fu_142_p4 <= ap_phi_reg_pp0_iter1_sel_flag_1_reg_138;
        end if; 
    end process;


    ap_phi_mux_sel_flag_2_phi_fu_164_p4_assign_proc : process(empty_reg_114, icmp_ln38_reg_607, ap_phi_reg_pp0_iter1_sel_flag_0_reg_125, ap_phi_reg_pp0_iter1_sel_flag_2_reg_160)
    begin
        if (((empty_reg_114 = ap_const_lv1_0) and (icmp_ln38_reg_607 = ap_const_lv1_0))) then 
            ap_phi_mux_sel_flag_2_phi_fu_164_p4 <= ap_phi_reg_pp0_iter1_sel_flag_0_reg_125;
        else 
            ap_phi_mux_sel_flag_2_phi_fu_164_p4 <= ap_phi_reg_pp0_iter1_sel_flag_2_reg_160;
        end if; 
    end process;


    ap_phi_mux_sel_flag_3_phi_fu_185_p4_assign_proc : process(empty_reg_114, icmp_ln38_reg_607, buff1_cnt_V_load_reg_611, ap_phi_mux_sel_flag_1_phi_fu_142_p4, ap_phi_mux_sel_flag_2_phi_fu_164_p4, ap_phi_reg_pp0_iter1_sel_flag_3_reg_182)
    begin
        if ((((empty_reg_114 = ap_const_lv1_0) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_0) and (icmp_ln38_reg_607 = ap_const_lv1_1)) or ((empty_reg_114 = ap_const_lv1_1) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_0) and (icmp_ln38_reg_607 = ap_const_lv1_0)))) then 
            ap_phi_mux_sel_flag_3_phi_fu_185_p4 <= ap_phi_mux_sel_flag_1_phi_fu_142_p4;
        elsif ((((empty_reg_114 = ap_const_lv1_0) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_0) and (icmp_ln38_reg_607 = ap_const_lv1_0)) or ((empty_reg_114 = ap_const_lv1_1) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_0) and (icmp_ln38_reg_607 = ap_const_lv1_1)))) then 
            ap_phi_mux_sel_flag_3_phi_fu_185_p4 <= ap_phi_mux_sel_flag_2_phi_fu_164_p4;
        else 
            ap_phi_mux_sel_flag_3_phi_fu_185_p4 <= ap_phi_reg_pp0_iter1_sel_flag_3_reg_182;
        end if; 
    end process;


    ap_phi_mux_sel_flag_4_phi_fu_218_p4_assign_proc : process(empty_reg_114, icmp_ln38_reg_607, buff1_cnt_V_load_reg_611, ap_phi_mux_sel_flag_1_phi_fu_142_p4, ap_phi_mux_sel_flag_2_phi_fu_164_p4, ap_phi_reg_pp0_iter1_sel_flag_4_reg_215)
    begin
        if ((((empty_reg_114 = ap_const_lv1_0) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_1) and (icmp_ln38_reg_607 = ap_const_lv1_1)) or ((empty_reg_114 = ap_const_lv1_1) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_1) and (icmp_ln38_reg_607 = ap_const_lv1_0)))) then 
            ap_phi_mux_sel_flag_4_phi_fu_218_p4 <= ap_phi_mux_sel_flag_1_phi_fu_142_p4;
        elsif ((((empty_reg_114 = ap_const_lv1_0) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_1) and (icmp_ln38_reg_607 = ap_const_lv1_0)) or ((empty_reg_114 = ap_const_lv1_1) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_1) and (icmp_ln38_reg_607 = ap_const_lv1_1)))) then 
            ap_phi_mux_sel_flag_4_phi_fu_218_p4 <= ap_phi_mux_sel_flag_2_phi_fu_164_p4;
        else 
            ap_phi_mux_sel_flag_4_phi_fu_218_p4 <= ap_phi_reg_pp0_iter1_sel_flag_4_reg_215;
        end if; 
    end process;


    ap_phi_mux_sel_flag_5_phi_fu_251_p4_assign_proc : process(buff1_cnt_V_load_reg_611, ap_phi_mux_sel_flag_3_phi_fu_185_p4, ap_phi_mux_sel_flag_4_phi_fu_218_p4, ap_phi_reg_pp0_iter1_sel_flag_5_reg_248)
    begin
        if ((buff1_cnt_V_load_reg_611 = ap_const_lv1_0)) then 
            ap_phi_mux_sel_flag_5_phi_fu_251_p4 <= ap_phi_mux_sel_flag_3_phi_fu_185_p4;
        elsif ((buff1_cnt_V_load_reg_611 = ap_const_lv1_1)) then 
            ap_phi_mux_sel_flag_5_phi_fu_251_p4 <= ap_phi_mux_sel_flag_4_phi_fu_218_p4;
        else 
            ap_phi_mux_sel_flag_5_phi_fu_251_p4 <= ap_phi_reg_pp0_iter1_sel_flag_5_reg_248;
        end if; 
    end process;


    ap_phi_mux_sel_new_1_phi_fu_153_p4_assign_proc : process(empty_reg_114, icmp_ln38_reg_607, ap_phi_reg_pp0_iter1_sel_new_1_reg_150)
    begin
        if (((empty_reg_114 = ap_const_lv1_1) and (icmp_ln38_reg_607 = ap_const_lv1_0))) then 
            ap_phi_mux_sel_new_1_phi_fu_153_p4 <= ap_const_lv1_1;
        else 
            ap_phi_mux_sel_new_1_phi_fu_153_p4 <= ap_phi_reg_pp0_iter1_sel_new_1_reg_150;
        end if; 
    end process;


    ap_phi_mux_sel_new_2_phi_fu_175_p4_assign_proc : process(empty_reg_114, icmp_ln38_reg_607, ap_phi_reg_pp0_iter1_sel_new_2_reg_172)
    begin
        if (((empty_reg_114 = ap_const_lv1_0) and (icmp_ln38_reg_607 = ap_const_lv1_0))) then 
            ap_phi_mux_sel_new_2_phi_fu_175_p4 <= ap_const_lv1_1;
        else 
            ap_phi_mux_sel_new_2_phi_fu_175_p4 <= ap_phi_reg_pp0_iter1_sel_new_2_reg_172;
        end if; 
    end process;


    ap_phi_mux_sel_new_3_phi_fu_196_p4_assign_proc : process(empty_reg_114, icmp_ln38_reg_607, buff1_cnt_V_load_reg_611, ap_phi_mux_sel_new_1_phi_fu_153_p4, ap_phi_mux_sel_new_2_phi_fu_175_p4, ap_phi_reg_pp0_iter1_sel_new_3_reg_193)
    begin
        if ((((empty_reg_114 = ap_const_lv1_0) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_0) and (icmp_ln38_reg_607 = ap_const_lv1_1)) or ((empty_reg_114 = ap_const_lv1_1) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_0) and (icmp_ln38_reg_607 = ap_const_lv1_0)))) then 
            ap_phi_mux_sel_new_3_phi_fu_196_p4 <= ap_phi_mux_sel_new_1_phi_fu_153_p4;
        elsif ((((empty_reg_114 = ap_const_lv1_0) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_0) and (icmp_ln38_reg_607 = ap_const_lv1_0)) or ((empty_reg_114 = ap_const_lv1_1) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_0) and (icmp_ln38_reg_607 = ap_const_lv1_1)))) then 
            ap_phi_mux_sel_new_3_phi_fu_196_p4 <= ap_phi_mux_sel_new_2_phi_fu_175_p4;
        else 
            ap_phi_mux_sel_new_3_phi_fu_196_p4 <= ap_phi_reg_pp0_iter1_sel_new_3_reg_193;
        end if; 
    end process;


    ap_phi_mux_sel_new_4_phi_fu_229_p4_assign_proc : process(empty_reg_114, icmp_ln38_reg_607, buff1_cnt_V_load_reg_611, ap_phi_mux_sel_new_1_phi_fu_153_p4, ap_phi_mux_sel_new_2_phi_fu_175_p4, ap_phi_reg_pp0_iter1_sel_new_4_reg_226)
    begin
        if ((((empty_reg_114 = ap_const_lv1_0) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_1) and (icmp_ln38_reg_607 = ap_const_lv1_1)) or ((empty_reg_114 = ap_const_lv1_1) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_1) and (icmp_ln38_reg_607 = ap_const_lv1_0)))) then 
            ap_phi_mux_sel_new_4_phi_fu_229_p4 <= ap_phi_mux_sel_new_1_phi_fu_153_p4;
        elsif ((((empty_reg_114 = ap_const_lv1_0) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_1) and (icmp_ln38_reg_607 = ap_const_lv1_0)) or ((empty_reg_114 = ap_const_lv1_1) and (buff1_cnt_V_load_reg_611 = ap_const_lv1_1) and (icmp_ln38_reg_607 = ap_const_lv1_1)))) then 
            ap_phi_mux_sel_new_4_phi_fu_229_p4 <= ap_phi_mux_sel_new_2_phi_fu_175_p4;
        else 
            ap_phi_mux_sel_new_4_phi_fu_229_p4 <= ap_phi_reg_pp0_iter1_sel_new_4_reg_226;
        end if; 
    end process;


    ap_phi_mux_sel_new_5_phi_fu_262_p4_assign_proc : process(buff1_cnt_V_load_reg_611, ap_phi_mux_sel_new_3_phi_fu_196_p4, ap_phi_mux_sel_new_4_phi_fu_229_p4, ap_phi_reg_pp0_iter1_sel_new_5_reg_259)
    begin
        if ((buff1_cnt_V_load_reg_611 = ap_const_lv1_0)) then 
            ap_phi_mux_sel_new_5_phi_fu_262_p4 <= ap_phi_mux_sel_new_3_phi_fu_196_p4;
        elsif ((buff1_cnt_V_load_reg_611 = ap_const_lv1_1)) then 
            ap_phi_mux_sel_new_5_phi_fu_262_p4 <= ap_phi_mux_sel_new_4_phi_fu_229_p4;
        else 
            ap_phi_mux_sel_new_5_phi_fu_262_p4 <= ap_phi_reg_pp0_iter1_sel_new_5_reg_259;
        end if; 
    end process;


    ap_phi_mux_tmp_5_phi_fu_304_p4_assign_proc : process(buff0_read_data_V, buff0_cnt_V_load_reg_636, trunc_ln674_3_fu_539_p1, ap_phi_reg_pp0_iter2_tmp_5_reg_301)
    begin
        if ((buff0_cnt_V_load_reg_636 = ap_const_lv1_1)) then 
            ap_phi_mux_tmp_5_phi_fu_304_p4 <= buff0_read_data_V(15 downto 8);
        elsif ((buff0_cnt_V_load_reg_636 = ap_const_lv1_0)) then 
            ap_phi_mux_tmp_5_phi_fu_304_p4 <= trunc_ln674_3_fu_539_p1;
        else 
            ap_phi_mux_tmp_5_phi_fu_304_p4 <= ap_phi_reg_pp0_iter2_tmp_5_reg_301;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_empty_reg_114 <= "X";
    ap_phi_reg_pp0_iter0_sel_flag_0_reg_125 <= "X";
    ap_phi_reg_pp0_iter0_sel_flag_1_reg_138 <= "X";
    ap_phi_reg_pp0_iter0_sel_flag_2_reg_160 <= "X";
    ap_phi_reg_pp0_iter0_sel_new_1_reg_150 <= "X";
    ap_phi_reg_pp0_iter0_sel_new_2_reg_172 <= "X";
    ap_phi_reg_pp0_iter0_tmp_4_reg_292 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter1_buff0_write_data_V_loc_0_reg_282 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_empty_19_reg_204 <= "X";
    ap_phi_reg_pp0_iter1_empty_20_reg_270 <= "X";
    ap_phi_reg_pp0_iter1_p_ph_reg_237 <= "X";
    ap_phi_reg_pp0_iter1_sel_flag_3_reg_182 <= "X";
    ap_phi_reg_pp0_iter1_sel_flag_4_reg_215 <= "X";
    ap_phi_reg_pp0_iter1_sel_flag_5_reg_248 <= "X";
    ap_phi_reg_pp0_iter1_sel_new_3_reg_193 <= "X";
    ap_phi_reg_pp0_iter1_sel_new_4_reg_226 <= "X";
    ap_phi_reg_pp0_iter1_sel_new_5_reg_259 <= "X";
    ap_phi_reg_pp0_iter2_tmp_5_reg_301 <= "XXXXXXXX";

    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to1 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= select_ln45_fu_559_p3;
    ap_return_1 <= select_ln46_fu_567_p3;
    ap_return_2 <= din_read_reg_597_pp0_iter1_reg;

    ap_sig_allocacmp_sel_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, sel, ap_phi_mux_sel_flag_5_phi_fu_251_p4, ap_phi_mux_sel_new_5_phi_fu_262_p4, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_phi_mux_sel_flag_5_phi_fu_251_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_sel_load <= ap_phi_mux_sel_new_5_phi_fu_262_p4;
        else 
            ap_sig_allocacmp_sel_load <= sel;
        end if; 
    end process;

    buff0_cnt_V_load_load_fu_453_p1 <= buff0_cnt_V;

    buff0_ram_V_address0_assign_proc : process(buff0_cnt_V_load_load_fu_453_p1, ap_phi_mux_empty_20_phi_fu_273_p4, zext_ln52_1_fu_511_p1, zext_ln56_1_fu_516_p1, ap_condition_273)
    begin
        if ((ap_const_boolean_1 = ap_condition_273)) then
            if (((ap_phi_mux_empty_20_phi_fu_273_p4 = ap_const_lv1_0) and (buff0_cnt_V_load_load_fu_453_p1 = ap_const_lv1_1))) then 
                buff0_ram_V_address0 <= zext_ln56_1_fu_516_p1(9 - 1 downto 0);
            elsif ((buff0_cnt_V_load_load_fu_453_p1 = ap_const_lv1_0)) then 
                buff0_ram_V_address0 <= zext_ln52_1_fu_511_p1(9 - 1 downto 0);
            else 
                buff0_ram_V_address0 <= "XXXXXXXXX";
            end if;
        else 
            buff0_ram_V_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    buff0_ram_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001, buff0_cnt_V_load_load_fu_453_p1, ap_phi_mux_empty_20_phi_fu_273_p4)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_phi_mux_empty_20_phi_fu_273_p4 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (buff0_cnt_V_load_load_fu_453_p1 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (buff0_cnt_V_load_load_fu_453_p1 = ap_const_lv1_0)))) then 
            buff0_ram_V_ce0 <= ap_const_logic_1;
        else 
            buff0_ram_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buff0_ram_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001, buff0_cnt_V_load_load_fu_453_p1, ap_phi_mux_empty_20_phi_fu_273_p4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_phi_mux_empty_20_phi_fu_273_p4 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (buff0_cnt_V_load_load_fu_453_p1 = ap_const_lv1_1))) then 
            buff0_ram_V_we0 <= ap_const_logic_1;
        else 
            buff0_ram_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buff1_cnt_V_load_load_fu_350_p1 <= buff1_cnt_V;

    buff1_ram_V_address0_assign_proc : process(buff1_cnt_V_load_load_fu_350_p1, zext_ln56_fu_407_p1, zext_ln52_fu_412_p1, ap_condition_268, ap_condition_262)
    begin
        if ((ap_const_boolean_1 = ap_condition_262)) then
            if ((buff1_cnt_V_load_load_fu_350_p1 = ap_const_lv1_0)) then 
                buff1_ram_V_address0 <= zext_ln52_fu_412_p1(9 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_268)) then 
                buff1_ram_V_address0 <= zext_ln56_fu_407_p1(9 - 1 downto 0);
            else 
                buff1_ram_V_address0 <= "XXXXXXXXX";
            end if;
        else 
            buff1_ram_V_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    buff1_ram_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001, icmp_ln38_fu_344_p2, buff1_cnt_V_load_load_fu_350_p1, ap_phi_mux_empty_phi_fu_117_p4)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((ap_phi_mux_empty_phi_fu_117_p4 = ap_const_lv1_1) and (buff1_cnt_V_load_load_fu_350_p1 = ap_const_lv1_1) and (icmp_ln38_fu_344_p2 = ap_const_lv1_0)) or ((ap_phi_mux_empty_phi_fu_117_p4 = ap_const_lv1_0) and (buff1_cnt_V_load_load_fu_350_p1 = ap_const_lv1_1) and (icmp_ln38_fu_344_p2 = ap_const_lv1_1)))) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (buff1_cnt_V_load_load_fu_350_p1 = ap_const_lv1_0)))) then 
            buff1_ram_V_ce0 <= ap_const_logic_1;
        else 
            buff1_ram_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buff1_ram_V_d0 <= (din & trunc_ln674_fu_388_p1);

    buff1_ram_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001, icmp_ln38_fu_344_p2, buff1_cnt_V_load_load_fu_350_p1, ap_phi_mux_empty_phi_fu_117_p4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((ap_phi_mux_empty_phi_fu_117_p4 = ap_const_lv1_1) and (buff1_cnt_V_load_load_fu_350_p1 = ap_const_lv1_1) and (icmp_ln38_fu_344_p2 = ap_const_lv1_0)) or ((ap_phi_mux_empty_phi_fu_117_p4 = ap_const_lv1_0) and (buff1_cnt_V_load_load_fu_350_p1 = ap_const_lv1_1) and (icmp_ln38_fu_344_p2 = ap_const_lv1_1))))) then 
            buff1_ram_V_we0 <= ap_const_logic_1;
        else 
            buff1_ram_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_310_p4 <= c(9 downto 1);
    grp_fu_320_p4 <= c_read_reg_592(9 downto 1);
    guard_variable_for_buff_ap_uint_8_int_ap_uint_8_sel_load_load_fu_329_p1 <= guard_variable_for_buff_ap_uint_8_int_ap_uint_8_sel;
    icmp_ln38_fu_344_p2 <= "1" when (c = ap_const_lv10_0) else "0";
    ret_1_fu_374_p3 <= (tmp_fu_364_p4 & din);
    ret_2_fu_472_p3 <= (din_read_reg_597 & trunc_ln674_2_fu_468_p1);
    ret_3_fu_489_p3 <= (tmp_2_fu_479_p4 & din_read_reg_597);
    ret_4_fu_496_p3 <= 
        ret_2_fu_472_p3 when (buff0_cnt_V(0) = '1') else 
        ret_3_fu_489_p3;
    ret_fu_392_p3 <= (din & trunc_ln674_fu_388_p1);
    select_ln45_fu_559_p3 <= 
        ap_phi_reg_pp0_iter2_tmp_4_reg_292 when (empty_20_reg_270(0) = '1') else 
        ap_phi_mux_tmp_5_phi_fu_304_p4;
    select_ln46_fu_567_p3 <= 
        ap_phi_mux_tmp_5_phi_fu_304_p4 when (empty_20_reg_270(0) = '1') else 
        ap_phi_reg_pp0_iter2_tmp_4_reg_292;
    tmp_2_fu_479_p4 <= buff0_write_data_V(15 downto 8);
    tmp_fu_364_p4 <= buff1_write_data_V(15 downto 8);
    trunc_ln674_1_fu_435_p1 <= buff1_ram_V_q0(8 - 1 downto 0);
    trunc_ln674_2_fu_468_p1 <= buff0_write_data_V(8 - 1 downto 0);
    trunc_ln674_3_fu_539_p1 <= buff0_ram_V_q0(8 - 1 downto 0);
    trunc_ln674_fu_388_p1 <= buff1_write_data_V(8 - 1 downto 0);
    xor_ln885_1_fu_521_p2 <= (buff0_cnt_V xor ap_const_lv1_1);
    xor_ln885_2_fu_354_p2 <= (ap_phi_mux_empty_phi_fu_117_p4 xor ap_const_lv1_1);
    xor_ln885_fu_417_p2 <= (buff1_cnt_V xor ap_const_lv1_1);
    zext_ln52_1_fu_511_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_320_p4),64));
    zext_ln52_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_310_p4),64));
    zext_ln56_1_fu_516_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_320_p4),64));
    zext_ln56_fu_407_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_310_p4),64));
end behav;
