-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity word_width_manual_word_width_manual_Pipeline_LOAD is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_idx_V_load : IN STD_LOGIC_VECTOR (20 downto 0);
    x_write3_V_load : IN STD_LOGIC_VECTOR (23 downto 0);
    x_sel_wr_V_load : IN STD_LOGIC_VECTOR (1 downto 0);
    x_in_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    x_in_EN_A : OUT STD_LOGIC;
    x_in_WEN_A : OUT STD_LOGIC_VECTOR (0 downto 0);
    x_in_Din_A : OUT STD_LOGIC_VECTOR (7 downto 0);
    x_in_Dout_A : IN STD_LOGIC_VECTOR (7 downto 0);
    x_idx_V_flag_0_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    x_idx_V_flag_0_out_ap_vld : OUT STD_LOGIC;
    x_idx_V_new_0_out : OUT STD_LOGIC_VECTOR (20 downto 0);
    x_idx_V_new_0_out_ap_vld : OUT STD_LOGIC;
    p_Val2_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    p_Val2_out_ap_vld : OUT STD_LOGIC;
    p_out : OUT STD_LOGIC_VECTOR (1 downto 0);
    p_out_ap_vld : OUT STD_LOGIC;
    x_x_V_address0 : OUT STD_LOGIC_VECTOR (18 downto 0);
    x_x_V_ce0 : OUT STD_LOGIC;
    x_x_V_we0 : OUT STD_LOGIC;
    x_x_V_d0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
end;


architecture behav of word_width_manual_word_width_manual_Pipeline_LOAD is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv21_12C000 : STD_LOGIC_VECTOR (20 downto 0) := "100101100000000000000";
    constant ap_const_lv21_1 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv21_64000 : STD_LOGIC_VECTOR (20 downto 0) := "001100100000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv24_FFFFFF : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111111111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln20_fu_220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_load_reg_560 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln1064_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1064_reg_570 : STD_LOGIC_VECTOR (0 downto 0);
    signal t_V_1_load_reg_574 : STD_LOGIC_VECTOR (20 downto 0);
    signal icmp_ln1064_2_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1064_2_reg_579 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln587_fu_235_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln587_1_fu_454_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_V_fu_96 : STD_LOGIC_VECTOR (20 downto 0);
    signal i_fu_226_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal empty_fu_100 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln885_fu_240_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Val2_s_fu_104 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Result_s_fu_447_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal t_V_1_fu_108 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln885_2_fu_260_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal select_ln18_1_fu_295_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_sig_allocacmp_t_V_1_load_1 : STD_LOGIC_VECTOR (20 downto 0);
    signal x_idx_V_new_0_fu_112 : STD_LOGIC_VECTOR (20 downto 0);
    signal select_ln18_fu_469_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal x_idx_V_flag_0_fu_116 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln18_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal x_in_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal Lo_fu_316_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal Hi_fu_323_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln414_fu_333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln414_fu_339_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln414_fu_345_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln414_2_fu_361_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln414_1_fu_353_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln414_1_fu_369_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln232_fu_329_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln414_fu_375_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal shl_ln414_fu_387_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_fu_393_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln414_1_fu_379_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln414_2_fu_383_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal shl_ln414_1_fu_411_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal lshr_ln414_fu_417_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal and_ln414_fu_423_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal xor_ln414_fu_429_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln414_3_fu_403_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal and_ln414_1_fu_435_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal and_ln414_2_fu_441_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_357 : BOOLEAN;
    signal ap_condition_360 : BOOLEAN;
    signal ap_condition_364 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component word_width_manual_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component word_width_manual_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    empty_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_fu_100 <= x_sel_wr_V_load;
                elsif ((ap_const_boolean_1 = ap_condition_360)) then 
                    empty_fu_100 <= ap_const_lv2_0;
                elsif ((ap_const_boolean_1 = ap_condition_357)) then 
                    empty_fu_100 <= add_ln885_fu_240_p2;
                end if;
            end if; 
        end if;
    end process;

    i_V_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_V_fu_96 <= ap_const_lv21_0;
                elsif (((icmp_ln20_fu_220_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_V_fu_96 <= i_fu_226_p2;
                end if;
            end if; 
        end if;
    end process;

    p_Val2_s_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    p_Val2_s_fu_104 <= x_write3_V_load;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    p_Val2_s_fu_104 <= p_Result_s_fu_447_p2;
                end if;
            end if; 
        end if;
    end process;

    t_V_1_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    t_V_1_fu_108 <= x_idx_V_load;
                elsif (((icmp_ln20_fu_220_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    t_V_1_fu_108 <= select_ln18_1_fu_295_p3;
                elsif ((ap_const_boolean_1 = ap_condition_360)) then 
                    t_V_1_fu_108 <= add_ln885_2_fu_260_p2;
                end if;
            end if; 
        end if;
    end process;

    x_idx_V_flag_0_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    x_idx_V_flag_0_fu_116 <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_condition_364)) then 
                    x_idx_V_flag_0_fu_116 <= ap_const_lv1_1;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    x_idx_V_flag_0_fu_116 <= or_ln18_fu_464_p2;
                end if;
            end if; 
        end if;
    end process;

    x_idx_V_new_0_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if ((ap_const_boolean_1 = ap_condition_364)) then 
                    x_idx_V_new_0_fu_112 <= add_ln885_2_fu_260_p2;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    x_idx_V_new_0_fu_112 <= select_ln18_fu_469_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_fu_220_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln1064_2_reg_579 <= icmp_ln1064_2_fu_289_p2;
                icmp_ln1064_reg_570 <= icmp_ln1064_fu_246_p2;
                p_load_reg_560 <= empty_fu_100;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1064_fu_246_p2 = ap_const_lv1_1) and (icmp_ln20_fu_220_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                t_V_1_load_reg_574 <= t_V_1_fu_108;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Hi_fu_323_p2 <= (ap_const_lv5_7 or Lo_fu_316_p3);
    Lo_fu_316_p3 <= (p_load_reg_560 & ap_const_lv3_0);
    add_ln885_2_fu_260_p2 <= std_logic_vector(unsigned(t_V_1_fu_108) + unsigned(ap_const_lv21_1));
    add_ln885_fu_240_p2 <= std_logic_vector(unsigned(empty_fu_100) + unsigned(ap_const_lv2_1));
    and_ln414_1_fu_435_p2 <= (xor_ln414_fu_429_p2 and p_Val2_s_fu_104);
    and_ln414_2_fu_441_p2 <= (select_ln414_3_fu_403_p3 and and_ln414_fu_423_p2);
    and_ln414_fu_423_p2 <= (shl_ln414_1_fu_411_p2 and lshr_ln414_fu_417_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_357_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln20_fu_220_p2, icmp_ln1064_fu_246_p2)
    begin
                ap_condition_357 <= ((icmp_ln1064_fu_246_p2 = ap_const_lv1_0) and (icmp_ln20_fu_220_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_360_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln20_fu_220_p2, icmp_ln1064_fu_246_p2)
    begin
                ap_condition_360 <= ((icmp_ln1064_fu_246_p2 = ap_const_lv1_1) and (icmp_ln20_fu_220_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_364_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln20_fu_220_p2, icmp_ln1064_fu_246_p2)
    begin
                ap_condition_364 <= ((icmp_ln1064_fu_246_p2 = ap_const_lv1_1) and (icmp_ln20_fu_220_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln20_fu_220_p2)
    begin
        if (((icmp_ln20_fu_220_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_t_V_1_load_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln20_fu_220_p2, icmp_ln1064_fu_246_p2, ap_block_pp0_stage0, t_V_1_fu_108, add_ln885_2_fu_260_p2)
    begin
        if (((icmp_ln1064_fu_246_p2 = ap_const_lv1_1) and (icmp_ln20_fu_220_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_t_V_1_load_1 <= add_ln885_2_fu_260_p2;
        else 
            ap_sig_allocacmp_t_V_1_load_1 <= t_V_1_fu_108;
        end if; 
    end process;

    i_fu_226_p2 <= std_logic_vector(unsigned(i_V_fu_96) + unsigned(ap_const_lv21_1));
    icmp_ln1064_2_fu_289_p2 <= "1" when (ap_sig_allocacmp_t_V_1_load_1 = ap_const_lv21_64000) else "0";
    icmp_ln1064_fu_246_p2 <= "1" when (add_ln885_fu_240_p2 = ap_const_lv2_3) else "0";
    icmp_ln20_fu_220_p2 <= "1" when (i_V_fu_96 = ap_const_lv21_12C000) else "0";
    icmp_ln414_fu_333_p2 <= "1" when (unsigned(Lo_fu_316_p3) > unsigned(Hi_fu_323_p2)) else "0";
    lshr_ln414_fu_417_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv24_FFFFFF),to_integer(unsigned('0' & zext_ln414_2_fu_383_p1(24-1 downto 0)))));
    or_ln18_fu_464_p2 <= (x_idx_V_flag_0_fu_116 or icmp_ln1064_2_reg_579);
    p_Result_s_fu_447_p2 <= (and_ln414_2_fu_441_p2 or and_ln414_1_fu_435_p2);
    p_Val2_out <= p_Val2_s_fu_104;

    p_Val2_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln20_fu_220_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln20_fu_220_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_Val2_out_ap_vld <= ap_const_logic_1;
        else 
            p_Val2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out <= empty_fu_100;

    p_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln20_fu_220_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln20_fu_220_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out_ap_vld <= ap_const_logic_1;
        else 
            p_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln18_1_fu_295_p3 <= 
        ap_const_lv21_0 when (icmp_ln1064_2_fu_289_p2(0) = '1') else 
        ap_sig_allocacmp_t_V_1_load_1;
    select_ln18_fu_469_p3 <= 
        ap_const_lv21_0 when (icmp_ln1064_2_reg_579(0) = '1') else 
        x_idx_V_new_0_fu_112;
    select_ln414_1_fu_353_p3 <= 
        Hi_fu_323_p2 when (icmp_ln414_fu_333_p2(0) = '1') else 
        Lo_fu_316_p3;
    select_ln414_2_fu_361_p3 <= 
        sub_ln414_fu_339_p2 when (icmp_ln414_fu_333_p2(0) = '1') else 
        Lo_fu_316_p3;
    select_ln414_3_fu_403_p3 <= 
        tmp_fu_393_p4 when (icmp_ln414_fu_333_p2(0) = '1') else 
        shl_ln414_fu_387_p2;
    select_ln414_fu_345_p3 <= 
        Lo_fu_316_p3 when (icmp_ln414_fu_333_p2(0) = '1') else 
        Hi_fu_323_p2;
    shl_ln414_1_fu_411_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv24_FFFFFF),to_integer(unsigned('0' & zext_ln414_1_fu_379_p1(24-1 downto 0)))));
    shl_ln414_fu_387_p2 <= std_logic_vector(shift_left(unsigned(zext_ln232_fu_329_p1),to_integer(unsigned('0' & zext_ln414_fu_375_p1(24-1 downto 0)))));
    sub_ln414_1_fu_369_p2 <= std_logic_vector(signed(ap_const_lv5_17) - signed(select_ln414_fu_345_p3));
    sub_ln414_fu_339_p2 <= std_logic_vector(signed(ap_const_lv5_17) - signed(Lo_fu_316_p3));
    
    tmp_fu_393_p4_proc : process(shl_ln414_fu_387_p2)
    variable vlo_cpy : STD_LOGIC_VECTOR(24+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(24+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(24 - 1 downto 0);
    variable tmp_fu_393_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(24 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(24 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(24 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_17(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        v0_cpy := shl_ln414_fu_387_p2;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(24-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(24-1-unsigned(ap_const_lv32_17(5-1 downto 0)));
            for tmp_fu_393_p4_i in 0 to 24-1 loop
                v0_cpy(tmp_fu_393_p4_i) := shl_ln414_fu_387_p2(24-1-tmp_fu_393_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(24-1 downto 0)))));
        res_mask := res_mask(24-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_fu_393_p4 <= resvalue(24-1 downto 0);
    end process;

    x_idx_V_flag_0_out <= x_idx_V_flag_0_fu_116;

    x_idx_V_flag_0_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln20_fu_220_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln20_fu_220_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_idx_V_flag_0_out_ap_vld <= ap_const_logic_1;
        else 
            x_idx_V_flag_0_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    x_idx_V_new_0_out <= x_idx_V_new_0_fu_112;

    x_idx_V_new_0_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln20_fu_220_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln20_fu_220_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_idx_V_new_0_out_ap_vld <= ap_const_logic_1;
        else 
            x_idx_V_new_0_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    x_in_Addr_A <= std_logic_vector(shift_left(unsigned(x_in_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_0(31-1 downto 0)))));
    x_in_Addr_A_orig <= zext_ln587_fu_235_p1(32 - 1 downto 0);
    x_in_Din_A <= ap_const_lv8_0;

    x_in_EN_A_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_in_EN_A <= ap_const_logic_1;
        else 
            x_in_EN_A <= ap_const_logic_0;
        end if; 
    end process;

    x_in_WEN_A <= ap_const_lv1_0;
    x_x_V_address0 <= zext_ln587_1_fu_454_p1(19 - 1 downto 0);

    x_x_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_x_V_ce0 <= ap_const_logic_1;
        else 
            x_x_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_x_V_d0 <= (and_ln414_2_fu_441_p2 or and_ln414_1_fu_435_p2);

    x_x_V_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln1064_reg_570)
    begin
        if (((icmp_ln1064_reg_570 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_x_V_we0 <= ap_const_logic_1;
        else 
            x_x_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln414_fu_429_p2 <= (ap_const_lv24_FFFFFF xor and_ln414_fu_423_p2);
    zext_ln232_fu_329_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_in_Dout_A),24));
    zext_ln414_1_fu_379_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln414_1_fu_353_p3),24));
    zext_ln414_2_fu_383_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln414_1_fu_369_p2),24));
    zext_ln414_fu_375_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln414_2_fu_361_p3),24));
    zext_ln587_1_fu_454_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_1_load_reg_574),64));
    zext_ln587_fu_235_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_V_fu_96),64));
end behav;
