#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_local_block", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_local_deadlock", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("x_in_Addr_A", 32, hls_out, 0, "bram", "MemPortADDR2", 1),
	Port_Property("x_in_EN_A", 1, hls_out, 0, "bram", "MemPortCE2", 1),
	Port_Property("x_in_WEN_A", 1, hls_out, 0, "bram", "MemPortWE2", 1),
	Port_Property("x_in_Din_A", 8, hls_out, 0, "bram", "MemPortDIN2", 1),
	Port_Property("x_in_Dout_A", 8, hls_in, 0, "bram", "MemPortDOUT2", 1),
	Port_Property("x_in_Clk_A", 1, hls_out, 0, "bram", "mem_clk", 1),
	Port_Property("x_in_Rst_A", 1, hls_out, 0, "bram", "mem_rst", 1),
	Port_Property("out_r_Addr_A", 32, hls_out, 1, "bram", "MemPortADDR2", 1),
	Port_Property("out_r_EN_A", 1, hls_out, 1, "bram", "MemPortCE2", 1),
	Port_Property("out_r_WEN_A", 1, hls_out, 1, "bram", "MemPortWE2", 1),
	Port_Property("out_r_Din_A", 8, hls_out, 1, "bram", "MemPortDIN2", 1),
	Port_Property("out_r_Dout_A", 8, hls_in, 1, "bram", "MemPortDOUT2", 1),
	Port_Property("out_r_Clk_A", 1, hls_out, 1, "bram", "mem_clk", 1),
	Port_Property("out_r_Rst_A", 1, hls_out, 1, "bram", "mem_rst", 1),
	Port_Property("load", 1, hls_in, 2, "ap_none", "in_data", 1),
};
const char* HLS_Design_Meta::dut_name = "BRAM_filter";
