#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_local_block", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("x_in_Addr_A", 32, hls_out, 0, "bram", "MemPortADDR2", 1),
	Port_Property("x_in_EN_A", 1, hls_out, 0, "bram", "MemPortCE2", 1),
	Port_Property("x_in_WEN_A", 1, hls_out, 0, "bram", "MemPortWE2", 1),
	Port_Property("x_in_Din_A", 8, hls_out, 0, "bram", "MemPortDIN2", 1),
	Port_Property("x_in_Dout_A", 8, hls_in, 0, "bram", "MemPortDOUT2", 1),
	Port_Property("x_in_Clk_A", 1, hls_out, 0, "bram", "mem_clk", 1),
	Port_Property("x_in_Rst_A", 1, hls_out, 0, "bram", "mem_rst", 1),
	Port_Property("y_Addr_A", 32, hls_out, 1, "bram", "MemPortADDR2", 1),
	Port_Property("y_EN_A", 1, hls_out, 1, "bram", "MemPortCE2", 1),
	Port_Property("y_WEN_A", 1, hls_out, 1, "bram", "MemPortWE2", 1),
	Port_Property("y_Din_A", 8, hls_out, 1, "bram", "MemPortDIN2", 1),
	Port_Property("y_Dout_A", 8, hls_in, 1, "bram", "MemPortDOUT2", 1),
	Port_Property("y_Clk_A", 1, hls_out, 1, "bram", "mem_clk", 1),
	Port_Property("y_Rst_A", 1, hls_out, 1, "bram", "mem_rst", 1),
	Port_Property("s_axi_control_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_AWADDR", 5, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_ARADDR", 5, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "interleave_manual_seq";
