-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity circular_shift_reg is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_local_block : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    dout_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    dout_EN_A : OUT STD_LOGIC;
    dout_WEN_A : OUT STD_LOGIC_VECTOR (0 downto 0);
    dout_Din_A : OUT STD_LOGIC_VECTOR (7 downto 0);
    dout_Dout_A : IN STD_LOGIC_VECTOR (7 downto 0);
    dout_Clk_A : OUT STD_LOGIC;
    dout_Rst_A : OUT STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of circular_shift_reg is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "circular_shift_reg_circular_shift_reg,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.959000,HLS_SYN_LAT=13,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=86,HLS_SYN_LUT=242,HLS_VERSION=2021_2}";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_local_deadlock : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_rst_reg_2 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_2 : signal is "no";
    signal ap_rst_reg_1 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_1 : signal is "no";
    signal ap_rst_n_inv : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_n_inv : signal is "no";
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_continue : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal din : STD_LOGIC_VECTOR (7 downto 0);
    signal regs_wptr_V : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal regs_mem_V_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal regs_mem_V_ce0 : STD_LOGIC;
    signal regs_mem_V_we0 : STD_LOGIC;
    signal regs_mem_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln70_fu_119_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln70_reg_129 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_start : STD_LOGIC;
    signal grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_done : STD_LOGIC;
    signal grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_idle : STD_LOGIC;
    signal grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_ready : STD_LOGIC;
    signal grp_circular_shift_reg_Pipeline_WRITE_fu_76_dout_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_circular_shift_reg_Pipeline_WRITE_fu_76_dout_EN_A : STD_LOGIC;
    signal grp_circular_shift_reg_Pipeline_WRITE_fu_76_dout_WEN_A : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_circular_shift_reg_Pipeline_WRITE_fu_76_dout_Din_A : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_circular_shift_reg_Pipeline_WRITE_fu_76_regs_mem_V_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_circular_shift_reg_Pipeline_WRITE_fu_76_regs_mem_V_ce0 : STD_LOGIC;
    signal grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal zext_ln587_fu_89_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln38_fu_105_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal add_ln885_fu_94_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln1064_fu_99_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component circular_shift_reg_circular_shift_reg_Pipeline_WRITE IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        add_ln70 : IN STD_LOGIC_VECTOR (4 downto 0);
        dout_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        dout_EN_A : OUT STD_LOGIC;
        dout_WEN_A : OUT STD_LOGIC_VECTOR (0 downto 0);
        dout_Din_A : OUT STD_LOGIC_VECTOR (7 downto 0);
        dout_Dout_A : IN STD_LOGIC_VECTOR (7 downto 0);
        regs_mem_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        regs_mem_V_ce0 : OUT STD_LOGIC;
        regs_mem_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component circular_shift_reg_regs_mem_V_RAM_T2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component circular_shift_reg_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        din : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_continue : OUT STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        ap_local_deadlock : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    regs_mem_V_U : component circular_shift_reg_regs_mem_V_RAM_T2P_BRAM_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 9,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => regs_mem_V_address0,
        ce0 => regs_mem_V_ce0,
        we0 => regs_mem_V_we0,
        d0 => din,
        q0 => regs_mem_V_q0);

    grp_circular_shift_reg_Pipeline_WRITE_fu_76 : component circular_shift_reg_circular_shift_reg_Pipeline_WRITE
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_start,
        ap_done => grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_done,
        ap_idle => grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_idle,
        ap_ready => grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_ready,
        add_ln70 => add_ln70_reg_129,
        dout_Addr_A => grp_circular_shift_reg_Pipeline_WRITE_fu_76_dout_Addr_A,
        dout_EN_A => grp_circular_shift_reg_Pipeline_WRITE_fu_76_dout_EN_A,
        dout_WEN_A => grp_circular_shift_reg_Pipeline_WRITE_fu_76_dout_WEN_A,
        dout_Din_A => grp_circular_shift_reg_Pipeline_WRITE_fu_76_dout_Din_A,
        dout_Dout_A => ap_const_lv8_0,
        regs_mem_V_address0 => grp_circular_shift_reg_Pipeline_WRITE_fu_76_regs_mem_V_address0,
        regs_mem_V_ce0 => grp_circular_shift_reg_Pipeline_WRITE_fu_76_regs_mem_V_ce0,
        regs_mem_V_q0 => regs_mem_V_q0);

    control_s_axi_U : component circular_shift_reg_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        din => din,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_continue => ap_continue,
        ap_idle => ap_idle,
        ap_local_deadlock => ap_local_deadlock);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_ready = ap_const_logic_1)) then 
                    grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_rst_n_inv_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_n_inv <= ap_rst_reg_1;
        end if;
    end process;

    ap_rst_reg_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_reg_1 <= ap_rst_reg_2;
        end if;
    end process;

    ap_rst_reg_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
                        ap_rst_reg_2 <= not(ap_rst_n);
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln70_reg_129 <= add_ln70_fu_119_p2;
                regs_wptr_V <= select_ln38_fu_105_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln70_fu_119_p2 <= std_logic_vector(unsigned(select_ln38_fu_105_p3) + unsigned(ap_const_lv5_1F));
    add_ln885_fu_94_p2 <= std_logic_vector(unsigned(regs_wptr_V) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_done)
    begin
        if ((grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_local_block <= ap_const_logic_0;
    ap_local_deadlock <= ap_const_lv1_0;

    ap_ready_assign_proc : process(grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    dout_Addr_A <= grp_circular_shift_reg_Pipeline_WRITE_fu_76_dout_Addr_A;
    dout_Clk_A <= ap_clk;
    dout_Din_A <= grp_circular_shift_reg_Pipeline_WRITE_fu_76_dout_Din_A;
    dout_EN_A <= grp_circular_shift_reg_Pipeline_WRITE_fu_76_dout_EN_A;
    dout_Rst_A <= ap_rst_n_inv;
    dout_WEN_A <= grp_circular_shift_reg_Pipeline_WRITE_fu_76_dout_WEN_A;
    grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_start <= grp_circular_shift_reg_Pipeline_WRITE_fu_76_ap_start_reg;
    icmp_ln1064_fu_99_p2 <= "1" when (add_ln885_fu_94_p2 = ap_const_lv5_9) else "0";

    regs_mem_V_address0_assign_proc : process(ap_CS_fsm_state1, grp_circular_shift_reg_Pipeline_WRITE_fu_76_regs_mem_V_address0, ap_CS_fsm_state3, zext_ln587_fu_89_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            regs_mem_V_address0 <= zext_ln587_fu_89_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            regs_mem_V_address0 <= grp_circular_shift_reg_Pipeline_WRITE_fu_76_regs_mem_V_address0;
        else 
            regs_mem_V_address0 <= "XXXX";
        end if; 
    end process;


    regs_mem_V_ce0_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, grp_circular_shift_reg_Pipeline_WRITE_fu_76_regs_mem_V_ce0, ap_CS_fsm_state3)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            regs_mem_V_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            regs_mem_V_ce0 <= grp_circular_shift_reg_Pipeline_WRITE_fu_76_regs_mem_V_ce0;
        else 
            regs_mem_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    regs_mem_V_we0_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            regs_mem_V_we0 <= ap_const_logic_1;
        else 
            regs_mem_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln38_fu_105_p3 <= 
        ap_const_lv5_0 when (icmp_ln1064_fu_99_p2(0) = '1') else 
        add_ln885_fu_94_p2;
    zext_ln587_fu_89_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(regs_wptr_V),64));
end behav;
