-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity img_interleave_manual_seq_read_seq is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    i : IN STD_LOGIC_VECTOR (16 downto 0);
    offset : IN STD_LOGIC_VECTOR (3 downto 0);
    x_x0_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    x_x0_V_ce0 : OUT STD_LOGIC;
    x_x0_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    x_x1_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    x_x1_V_ce0 : OUT STD_LOGIC;
    x_x1_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    x_x2_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    x_x2_V_ce0 : OUT STD_LOGIC;
    x_x2_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    x_x3_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    x_x3_V_ce0 : OUT STD_LOGIC;
    x_x3_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    x_x4_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    x_x4_V_ce0 : OUT STD_LOGIC;
    x_x4_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    x_x5_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    x_x5_V_ce0 : OUT STD_LOGIC;
    x_x5_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    x_x6_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    x_x6_V_ce0 : OUT STD_LOGIC;
    x_x6_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    x_x7_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    x_x7_V_ce0 : OUT STD_LOGIC;
    x_x7_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    x_x8_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    x_x8_V_ce0 : OUT STD_LOGIC;
    x_x8_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    x_x9_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    x_x9_V_ce0 : OUT STD_LOGIC;
    x_x9_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    x_x10_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    x_x10_V_ce0 : OUT STD_LOGIC;
    x_x10_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    x_x11_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    x_x11_V_ce0 : OUT STD_LOGIC;
    x_x11_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    x_x12_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    x_x12_V_ce0 : OUT STD_LOGIC;
    x_x12_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    x_x13_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    x_x13_V_ce0 : OUT STD_LOGIC;
    x_x13_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    x_x14_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    x_x14_V_ce0 : OUT STD_LOGIC;
    x_x14_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    x_x15_V_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    x_x15_V_ce0 : OUT STD_LOGIC;
    x_x15_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of img_interleave_manual_seq_read_seq is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal offset_read_reg_433 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_phi_mux_agg_result_0_phi_fu_303_p32 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_agg_result_0_reg_300 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln587_14_fu_353_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln587_13_fu_358_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_12_fu_363_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_11_fu_368_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_10_fu_373_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_9_fu_378_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_8_fu_383_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_7_fu_388_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_6_fu_393_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_5_fu_398_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_4_fu_403_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_3_fu_408_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_2_fu_413_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_1_fu_418_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_15_fu_423_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln587_fu_428_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_reset_start_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                offset_read_reg_433 <= offset;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0, ap_reset_start_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_agg_result_0_phi_fu_303_p32_assign_proc : process(x_x0_V_q0, x_x1_V_q0, x_x2_V_q0, x_x3_V_q0, x_x4_V_q0, x_x5_V_q0, x_x6_V_q0, x_x7_V_q0, x_x8_V_q0, x_x9_V_q0, x_x10_V_q0, x_x11_V_q0, x_x12_V_q0, x_x13_V_q0, x_x14_V_q0, x_x15_V_q0, offset_read_reg_433, ap_phi_reg_pp0_iter1_agg_result_0_reg_300)
    begin
        if ((offset_read_reg_433 = ap_const_lv4_0)) then 
            ap_phi_mux_agg_result_0_phi_fu_303_p32 <= x_x0_V_q0;
        elsif ((offset_read_reg_433 = ap_const_lv4_1)) then 
            ap_phi_mux_agg_result_0_phi_fu_303_p32 <= x_x1_V_q0;
        elsif ((offset_read_reg_433 = ap_const_lv4_2)) then 
            ap_phi_mux_agg_result_0_phi_fu_303_p32 <= x_x2_V_q0;
        elsif ((offset_read_reg_433 = ap_const_lv4_3)) then 
            ap_phi_mux_agg_result_0_phi_fu_303_p32 <= x_x3_V_q0;
        elsif ((offset_read_reg_433 = ap_const_lv4_4)) then 
            ap_phi_mux_agg_result_0_phi_fu_303_p32 <= x_x4_V_q0;
        elsif ((offset_read_reg_433 = ap_const_lv4_5)) then 
            ap_phi_mux_agg_result_0_phi_fu_303_p32 <= x_x5_V_q0;
        elsif ((offset_read_reg_433 = ap_const_lv4_6)) then 
            ap_phi_mux_agg_result_0_phi_fu_303_p32 <= x_x6_V_q0;
        elsif ((offset_read_reg_433 = ap_const_lv4_7)) then 
            ap_phi_mux_agg_result_0_phi_fu_303_p32 <= x_x7_V_q0;
        elsif ((offset_read_reg_433 = ap_const_lv4_8)) then 
            ap_phi_mux_agg_result_0_phi_fu_303_p32 <= x_x8_V_q0;
        elsif ((offset_read_reg_433 = ap_const_lv4_9)) then 
            ap_phi_mux_agg_result_0_phi_fu_303_p32 <= x_x9_V_q0;
        elsif ((offset_read_reg_433 = ap_const_lv4_A)) then 
            ap_phi_mux_agg_result_0_phi_fu_303_p32 <= x_x10_V_q0;
        elsif ((offset_read_reg_433 = ap_const_lv4_B)) then 
            ap_phi_mux_agg_result_0_phi_fu_303_p32 <= x_x11_V_q0;
        elsif ((offset_read_reg_433 = ap_const_lv4_C)) then 
            ap_phi_mux_agg_result_0_phi_fu_303_p32 <= x_x12_V_q0;
        elsif ((offset_read_reg_433 = ap_const_lv4_D)) then 
            ap_phi_mux_agg_result_0_phi_fu_303_p32 <= x_x13_V_q0;
        elsif ((offset_read_reg_433 = ap_const_lv4_E)) then 
            ap_phi_mux_agg_result_0_phi_fu_303_p32 <= x_x14_V_q0;
        elsif ((offset_read_reg_433 = ap_const_lv4_F)) then 
            ap_phi_mux_agg_result_0_phi_fu_303_p32 <= x_x15_V_q0;
        else 
            ap_phi_mux_agg_result_0_phi_fu_303_p32 <= ap_phi_reg_pp0_iter1_agg_result_0_reg_300;
        end if; 
    end process;

    ap_phi_reg_pp0_iter1_agg_result_0_reg_300 <= "XXXXXXXX";

    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_start_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_start_pp0 <= ap_const_logic_1;
        else 
            ap_reset_start_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= ap_phi_mux_agg_result_0_phi_fu_303_p32;
    x_x0_V_address0 <= zext_ln587_fu_428_p1(17 - 1 downto 0);

    x_x0_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_x0_V_ce0 <= ap_const_logic_1;
        else 
            x_x0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_x10_V_address0 <= zext_ln587_10_fu_373_p1(17 - 1 downto 0);

    x_x10_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_x10_V_ce0 <= ap_const_logic_1;
        else 
            x_x10_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_x11_V_address0 <= zext_ln587_11_fu_368_p1(17 - 1 downto 0);

    x_x11_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_x11_V_ce0 <= ap_const_logic_1;
        else 
            x_x11_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_x12_V_address0 <= zext_ln587_12_fu_363_p1(17 - 1 downto 0);

    x_x12_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_x12_V_ce0 <= ap_const_logic_1;
        else 
            x_x12_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_x13_V_address0 <= zext_ln587_13_fu_358_p1(17 - 1 downto 0);

    x_x13_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_x13_V_ce0 <= ap_const_logic_1;
        else 
            x_x13_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_x14_V_address0 <= zext_ln587_14_fu_353_p1(17 - 1 downto 0);

    x_x14_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_x14_V_ce0 <= ap_const_logic_1;
        else 
            x_x14_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_x15_V_address0 <= zext_ln587_15_fu_423_p1(17 - 1 downto 0);

    x_x15_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_x15_V_ce0 <= ap_const_logic_1;
        else 
            x_x15_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_x1_V_address0 <= zext_ln587_1_fu_418_p1(17 - 1 downto 0);

    x_x1_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_x1_V_ce0 <= ap_const_logic_1;
        else 
            x_x1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_x2_V_address0 <= zext_ln587_2_fu_413_p1(17 - 1 downto 0);

    x_x2_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_x2_V_ce0 <= ap_const_logic_1;
        else 
            x_x2_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_x3_V_address0 <= zext_ln587_3_fu_408_p1(17 - 1 downto 0);

    x_x3_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_x3_V_ce0 <= ap_const_logic_1;
        else 
            x_x3_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_x4_V_address0 <= zext_ln587_4_fu_403_p1(17 - 1 downto 0);

    x_x4_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_x4_V_ce0 <= ap_const_logic_1;
        else 
            x_x4_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_x5_V_address0 <= zext_ln587_5_fu_398_p1(17 - 1 downto 0);

    x_x5_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_x5_V_ce0 <= ap_const_logic_1;
        else 
            x_x5_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_x6_V_address0 <= zext_ln587_6_fu_393_p1(17 - 1 downto 0);

    x_x6_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_x6_V_ce0 <= ap_const_logic_1;
        else 
            x_x6_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_x7_V_address0 <= zext_ln587_7_fu_388_p1(17 - 1 downto 0);

    x_x7_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_x7_V_ce0 <= ap_const_logic_1;
        else 
            x_x7_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_x8_V_address0 <= zext_ln587_8_fu_383_p1(17 - 1 downto 0);

    x_x8_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_x8_V_ce0 <= ap_const_logic_1;
        else 
            x_x8_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_x9_V_address0 <= zext_ln587_9_fu_378_p1(17 - 1 downto 0);

    x_x9_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_x9_V_ce0 <= ap_const_logic_1;
        else 
            x_x9_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln587_10_fu_373_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i),64));
    zext_ln587_11_fu_368_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i),64));
    zext_ln587_12_fu_363_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i),64));
    zext_ln587_13_fu_358_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i),64));
    zext_ln587_14_fu_353_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i),64));
    zext_ln587_15_fu_423_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i),64));
    zext_ln587_1_fu_418_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i),64));
    zext_ln587_2_fu_413_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i),64));
    zext_ln587_3_fu_408_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i),64));
    zext_ln587_4_fu_403_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i),64));
    zext_ln587_5_fu_398_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i),64));
    zext_ln587_6_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i),64));
    zext_ln587_7_fu_388_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i),64));
    zext_ln587_8_fu_383_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i),64));
    zext_ln587_9_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i),64));
    zext_ln587_fu_428_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i),64));
end behav;
